name: Pull Request CI Check
on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup qemu
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Login to Docker Hub
      id: login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: build updated image
      run: |
        make -C docker PDK_ROOT=$(pwd)/pdks CACHE_ID=${{ secrets.DOCKER_HUB_USERNAME }} build-all
        make -C docker PDK_ROOT=$(pwd)/pdks CACHE_ID=${{ secrets.DOCKER_HUB_USERNAME }} openlane
    - name: Clean
      run: |
        rm -f ${HOME}/.docker/config.json
