name: Pull Request CI Check
on: [push, pull_request]
jobs:
  github-cache:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup qemu
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: docker/docker-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to Docker Hub
      id: login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#    - name: Build and push
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/openlane:latest
#        cache-from: type=local,src=/tmp/.buildx-cache
#        cache-to: type=local,dest=/tmp/.buildx-cache
    - name: build updated image
      run: |
        make PDK_ROOT=$(pwd)/pdks CACHE_ID=${{ secrets.DOCKER_HUB_USERNAME }} docker-cache
        make PDK_ROOT=$(pwd)/pdks CACHE_ID=${{ secrets.DOCKER_HUB_USERNAME }} openlane
    - name: Clean
      run: |
        rm -f ${HOME}/.docker/config.json
