name: Pull Request CI Check
on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup qemu
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
          platforms: all
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
       version: latest
    - name: login to docker hub
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
    - name: build updated image
      run: |
        make PDK_ROOT=$(pwd)/pdks docker-cache
        make PDK_ROOT=$(pwd)/pdks openlane
        .github/buildPDKs.sh
        make PDK_ROOT=$(pwd)/pdks test
    - name: Clean
      run: |
        rm -f ${HOME}/.docker/config.json
